on: 
  push:
    branches: main 
name: Check Repo
jobs:
  check-rmd:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install packages
      run: |
        R -e 'install.packages("quarto")'
    - name: Check qmd Rendering
      run:  Rscript -e "quarto::quarto_render('render-this.qmd')"
