on: 
  push:
    branches: main 
name: Check Repo
jobs:
  check-qmd:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Quarto Render
      uses: pommevilla/quarto-render@v0.3.11



